
services:
  app_local:
    build: .
    container_name: app_local
    restart: always
    ports:
      - "8070:8070"
    env_file:
      - .env
    depends_on:
      - postgres_local
      - redis_local

  postgres_local:
    image: postgres:15
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multilang1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_local:
    image: redis:7
    container_name: redis_local
    restart: always
    ports:
      - "6379:6379"

  pgadmin_local:
    image: adminer
    restart: always
    ports:
      - "9012:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=my_postgres


volumes:
  postgres_data: